var searchData=
[
  ['namedchar_0',['NamedChar',['../struct_harlinn_1_1_common_1_1_core_1_1_html_1_1_named_char.html',1,'Harlinn::Common::Core::Html']]],
  ['namednodemap_1',['NamedNodeMap',['../class_harlinn_1_1_common_1_1_core_1_1_xml_1_1_dom_1_1_named_node_map.html',1,'Harlinn::Common::Core::Xml::Dom']]],
  ['namedpropertystore_2',['NamedPropertyStore',['../class_harlinn_1_1_common_1_1_core_1_1_named_property_store.html',1,'Harlinn::Common::Core']]],
  ['namescope_3',['NameScope',['../class_harlinn_1_1_a_i_1_1_d_m_l_1_1_x_1_1_name_scope.html',1,'Harlinn::AI::DML::X']]],
  ['namespace_4',['Namespace',['../class_harlinn_1_1_common_1_1_core_1_1_doxygen_1_1_structure_1_1_namespace.html',1,'Harlinn::Common::Core::Doxygen::Structure']]],
  ['namevaluepairdescriptor_5',['NameValuePairDescriptor',['../class_harlinn_1_1_o_c_i_1_1_name_value_pair_descriptor.html',1,'Harlinn::OCI']]],
  ['nativefunctions_6',['NativeFunctions',['../class_harlinn_1_1_common_1_1_core_1_1_net_1_1_native_functions.html',1,'Harlinn::Common::Core::Net']]],
  ['nearlyequal_7',['NearlyEqual',['../struct_harlinn_1_1_a_i_1_1_o_n_n_x_1_1_nearly_equal.html',1,'Harlinn::AI::ONNX']]],
  ['negativeinfinityunsignedvalue_8',['NegativeInfinityUnsignedValue',['../struct_harlinn_1_1_common_1_1_core_1_1_math_1_1_internal_1_1_negative_infinity_unsigned_value.html',1,'Harlinn::Common::Core::Math::Internal']]],
  ['negativeinfinityunsignedvalue_3c_20double_20_3e_9',['NegativeInfinityUnsignedValue&lt; double &gt;',['../struct_harlinn_1_1_common_1_1_core_1_1_math_1_1_internal_1_1_negative_infinity_unsigned_value_3_01double_01_4.html',1,'Harlinn::Common::Core::Math::Internal']]],
  ['negativeinfinityunsignedvalue_3c_20float_20_3e_10',['NegativeInfinityUnsignedValue&lt; float &gt;',['../struct_harlinn_1_1_common_1_1_core_1_1_math_1_1_internal_1_1_negative_infinity_unsigned_value_3_01float_01_4.html',1,'Harlinn::Common::Core::Math::Internal']]],
  ['negotiateclientsecuritycontext_11',['NegotiateClientSecurityContext',['../class_harlinn_1_1_common_1_1_core_1_1_security_1_1_negotiate_client_security_context.html',1,'Harlinn::Common::Core::Security']]],
  ['negotiatesecuritycontext_12',['NegotiateSecurityContext',['../class_harlinn_1_1_common_1_1_core_1_1_security_1_1_negotiate_security_context.html',1,'Harlinn::Common::Core::Security']]],
  ['negotiateserversecuritycontext_13',['NegotiateServerSecurityContext',['../class_harlinn_1_1_common_1_1_core_1_1_security_1_1_negotiate_server_security_context.html',1,'Harlinn::Common::Core::Security']]],
  ['netapibuffer_14',['NetApiBuffer',['../class_harlinn_1_1_common_1_1_core_1_1_environment_1_1_internal_1_1_net_api_buffer.html',1,'Harlinn::Common::Core::Environment::Internal']]],
  ['node_15',['Node',['../class_harlinn_1_1_a_i_1_1_o_n_n_x_1_1_node.html',1,'Harlinn::AI::ONNX::Node'],['../struct_harlinn_1_1_common_1_1_core_1_1_list_1_1_node.html',1,'Harlinn::Common::Core::List&lt; T, nodeSize &gt;::Node'],['../class_harlinn_1_1_common_1_1_core_1_1_xml_1_1_dom_1_1_node.html',1,'Harlinn::Common::Core::Xml::Dom::Node'],['../struct_harlinn_1_1_windows_1_1_graphics_1_1_d3_d12_1_1_node.html',1,'Harlinn::Windows::Graphics::D3D12::Node']]],
  ['nodecpuinput_16',['NodeCPUInput',['../struct_harlinn_1_1_windows_1_1_graphics_1_1_d3_d12_1_1_node_c_p_u_input.html',1,'Harlinn::Windows::Graphics::D3D12']]],
  ['nodegpuinput_17',['NodeGPUInput',['../struct_harlinn_1_1_windows_1_1_graphics_1_1_d3_d12_1_1_node_g_p_u_input.html',1,'Harlinn::Windows::Graphics::D3D12']]],
  ['nodeid_18',['NodeID',['../struct_harlinn_1_1_a_i_1_1_d_m_l_1_1_x_1_1_internal_1_1_node_i_d.html',1,'Harlinn::AI::DML::X::Internal']]],
  ['nodeid_19',['NodeId',['../struct_harlinn_1_1_windows_1_1_graphics_1_1_d3_d12_1_1_node_id.html',1,'Harlinn::Windows::Graphics::D3D12']]],
  ['nodeinput_20',['NodeInput',['../class_harlinn_1_1_a_i_1_1_o_n_n_x_1_1_node_input.html',1,'Harlinn::AI::ONNX']]],
  ['nodeiterator_21',['NodeIterator',['../class_harlinn_1_1_common_1_1_core_1_1_xml_1_1_dom_1_1_node_iterator.html',1,'Harlinn::Common::Core::Xml::Dom']]],
  ['nodelist_22',['NodeList',['../class_harlinn_1_1_common_1_1_core_1_1_xml_1_1_dom_1_1_node_list.html',1,'Harlinn::Common::Core::Xml::Dom']]],
  ['nodemask_23',['NodeMask',['../struct_harlinn_1_1_windows_1_1_graphics_1_1_d3_d12_1_1_node_mask.html',1,'Harlinn::Windows::Graphics::D3D12']]],
  ['nodeoutput_24',['NodeOutput',['../class_harlinn_1_1_a_i_1_1_d_m_l_1_1_x_1_1_internal_1_1_node_output.html',1,'Harlinn::AI::DML::X::Internal::NodeOutput'],['../class_harlinn_1_1_a_i_1_1_o_n_n_x_1_1_node_output.html',1,'Harlinn::AI::ONNX::NodeOutput']]],
  ['nodeoutputoverrides_25',['NodeOutputOverrides',['../struct_harlinn_1_1_windows_1_1_graphics_1_1_d3_d12_1_1_node_output_overrides.html',1,'Harlinn::Windows::Graphics::D3D12']]],
  ['nodetype_26',['NodeType',['../class_harlinn_1_1_common_1_1_core_1_1_doxygen_1_1_node_type.html',1,'Harlinn::Common::Core::Doxygen']]],
  ['nomove_5fif_27',['nomove_if',['../struct_harlinn_1_1_common_1_1_core_1_1details_1_1nomove__if.html',1,'Harlinn::Common::Core::details']]],
  ['nomove_5fif_3c_20false_20_3e_28',['nomove_if&lt; false &gt;',['../struct_harlinn_1_1_common_1_1_core_1_1details_1_1nomove__if_3_01false_01_4.html',1,'Harlinn::Common::Core::details']]],
  ['nonclientmetrics_29',['NonClientMetrics',['../class_harlinn_1_1_windows_1_1_non_client_metrics.html',1,'Harlinn::Windows']]],
  ['nonzerocoordinatesoutputs_30',['NonZeroCoordinatesOutputs',['../struct_harlinn_1_1_a_i_1_1_d_m_l_1_1_x_1_1_non_zero_coordinates_outputs.html',1,'Harlinn::AI::DML::X']]],
  ['normal_31',['Normal',['../class_harlinn_1_1_math_1_1_normal.html',1,'Harlinn::Math']]],
  ['normal_3c_20float_2c_203_20_3e_32',['Normal&lt; float, 3 &gt;',['../class_harlinn_1_1_math_1_1_normal_3_01float_00_013_01_4.html',1,'Harlinn::Math']]],
  ['normalbase_33',['NormalBase',['../struct_harlinn_1_1_math_1_1_internal_1_1_normal_base.html',1,'Harlinn::Math::Internal']]],
  ['normalizedfloat_34',['NormalizedFloat',['../class_harlinn_1_1_common_1_1_core_1_1_math_1_1_normalized_float.html',1,'Harlinn::Common::Core::Math']]],
  ['notation_35',['Notation',['../class_harlinn_1_1_common_1_1_core_1_1_xml_1_1_dom_1_1_notation.html',1,'Harlinn::Common::Core::Xml::Dom']]],
  ['notfinitenumberexception_36',['NotFiniteNumberException',['../class_harlinn_1_1_common_1_1_core_1_1_not_finite_number_exception.html',1,'Harlinn::Common::Core']]],
  ['notificationentry_37',['NotificationEntry',['../class_harlinn_1_1_common_1_1_core_1_1_zero_mq_1_1_z_m_q_notification_server_1_1_notification_entry.html',1,'Harlinn::Common::Core::ZeroMq::ZMQNotificationServer']]],
  ['notificationmessage_38',['NotificationMessage',['../struct_harlinn_1_1_common_1_1_core_1_1_zero_mq_1_1_z_m_q_notification_server_1_1_notification_entry_1_1_notification_message.html',1,'Harlinn::Common::Core::ZeroMq::ZMQNotificationServer::NotificationEntry']]],
  ['notimplementedexception_39',['NotImplementedException',['../class_harlinn_1_1_common_1_1_core_1_1_not_implemented_exception.html',1,'Harlinn::Common::Core']]],
  ['notsupportedexception_40',['NotSupportedException',['../class_harlinn_1_1_common_1_1_core_1_1_not_supported_exception.html',1,'Harlinn::Common::Core']]],
  ['ntlmclientsecuritycontext_41',['NTLMClientSecurityContext',['../class_harlinn_1_1_common_1_1_core_1_1_security_1_1_n_t_l_m_client_security_context.html',1,'Harlinn::Common::Core::Security']]],
  ['ntlmsecuritycontext_42',['NTLMSecurityContext',['../class_harlinn_1_1_common_1_1_core_1_1_security_1_1_n_t_l_m_security_context.html',1,'Harlinn::Common::Core::Security']]],
  ['ntlmserversecuritycontext_43',['NTLMServerSecurityContext',['../class_harlinn_1_1_common_1_1_core_1_1_security_1_1_n_t_l_m_server_security_context.html',1,'Harlinn::Common::Core::Security']]],
  ['nullreferenceexception_44',['NullReferenceException',['../class_harlinn_1_1_common_1_1_core_1_1_null_reference_exception.html',1,'Harlinn::Common::Core']]],
  ['number_45',['Number',['../struct_harlinn_1_1_o_c_i_1_1_number.html',1,'Harlinn::OCI']]],
  ['numberarraybasedefine_46',['NumberArrayBaseDefine',['../class_harlinn_1_1_o_c_i_1_1_number_array_base_define.html',1,'Harlinn::OCI']]],
  ['numberbasedefine_47',['NumberBaseDefine',['../class_harlinn_1_1_o_c_i_1_1_number_base_define.html',1,'Harlinn::OCI']]],
  ['numeric_48',['Numeric',['../class_harlinn_1_1_o_d_b_c_1_1_numeric.html',1,'Harlinn::ODBC']]],
  ['numeric_5flimits_3c_20half_5ffloat_3a_3ahalf_20_3e_49',['numeric_limits&lt; half_float::half &gt;',['../classstd_1_1numeric__limits_3_01half__float_1_1half_01_4.html',1,'std']]],
  ['numerictest_50',['NumericTest',['../struct_harlinn_1_1_common_1_1_core_1_1_test_1_1_numeric_test.html',1,'Harlinn::Common::Core::Test']]]
];
