var namespace_harlinn_1_1_windows_1_1_direct_write =
[
    [ "BitmapRenderTarget", "class_harlinn_1_1_windows_1_1_direct_write_1_1_bitmap_render_target.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_bitmap_render_target" ],
    [ "Factory", "class_harlinn_1_1_windows_1_1_direct_write_1_1_factory.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_factory" ],
    [ "Font", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font" ],
    [ "FontCollection", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_collection.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_collection" ],
    [ "FontCollectionLoader", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_collection_loader.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_collection_loader" ],
    [ "FontFace", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_face.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_face" ],
    [ "FontFamily", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_family.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_family" ],
    [ "FontFile", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_file.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_file" ],
    [ "FontFileEnumerator", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_file_enumerator.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_file_enumerator" ],
    [ "FontFileLoader", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_file_loader.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_file_loader" ],
    [ "FontFileStream", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_file_stream.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_file_stream" ],
    [ "FontList", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_list.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_font_list" ],
    [ "GdiInterop", "class_harlinn_1_1_windows_1_1_direct_write_1_1_gdi_interop.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_gdi_interop" ],
    [ "GlyphRunAnalysis", "class_harlinn_1_1_windows_1_1_direct_write_1_1_glyph_run_analysis.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_glyph_run_analysis" ],
    [ "InlineObject", "class_harlinn_1_1_windows_1_1_direct_write_1_1_inline_object.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_inline_object" ],
    [ "LocalFontFileLoader", "class_harlinn_1_1_windows_1_1_direct_write_1_1_local_font_file_loader.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_local_font_file_loader" ],
    [ "LocalizedStrings", "class_harlinn_1_1_windows_1_1_direct_write_1_1_localized_strings.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_localized_strings" ],
    [ "PixelSnapping", "class_harlinn_1_1_windows_1_1_direct_write_1_1_pixel_snapping.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_pixel_snapping" ],
    [ "RenderingParams", "class_harlinn_1_1_windows_1_1_direct_write_1_1_rendering_params.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_rendering_params" ],
    [ "TextAnalysisSink", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_analysis_sink.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_analysis_sink" ],
    [ "TextAnalysisSource", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_analysis_source.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_analysis_source" ],
    [ "TextAnalyzer", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_analyzer.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_analyzer" ],
    [ "TextFormat", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_format.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_format" ],
    [ "TextLayout", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_layout.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_layout" ],
    [ "TextRenderer", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_renderer.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_text_renderer" ],
    [ "Typography", "class_harlinn_1_1_windows_1_1_direct_write_1_1_typography.xhtml", "class_harlinn_1_1_windows_1_1_direct_write_1_1_typography" ]
];