var namespace_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities =
[
    [ "BaseEntity", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_base_entity.xhtml", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_base_entity" ],
    [ "EntityContextBase", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_entity_context_base.xhtml", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_entity_context_base" ],
    [ "EntityContextEventArgs", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_entity_context_event_args.xhtml", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_entity_context_event_args" ],
    [ "EntityContextExceptionEventArgs", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_entity_context_exception_event_args.xhtml", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_entity_context_exception_event_args" ],
    [ "EventContextAfterCommitEventArgs", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_event_context_after_commit_event_args.xhtml", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_event_context_after_commit_event_args" ],
    [ "EventContextBeforeCommitEventArgs", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_event_context_before_commit_event_args.xhtml", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_event_context_before_commit_event_args" ],
    [ "EventContextEntityPropertyChangedEventArgs", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_event_context_entity_property_changed_event_args.xhtml", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_event_context_entity_property_changed_event_args" ],
    [ "EventContextUpdatedEventArgs", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_event_context_updated_event_args.xhtml", "class_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_event_context_updated_event_args" ],
    [ "IBaseEntityFactory", "interface_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_i_base_entity_factory.xhtml", "interface_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities_1_1_i_base_entity_factory" ],
    [ "EntityContextExceptionEventHandler< TKind >", "namespace_harlinn_1_1_common_1_1_core_1_1_net_1_1_entities.xhtml#a9c0d67235bc76a08aa1efb5edf26ba57", null ]
];